### ISSUE TITLE
project-manager-bilal.txt file have format issues. 

### ISSUE THREAD

**Issue by bilalajanjua** [bilalajanjua/change-management-lab-assignment-3#3]
#Format Issues
The file `project-manager-bilal.txt`  have format issues.
`Hadia Shahab     FA16-BSE-106     6b`
`Tarim Saleem  - (FA16-BSE-092)`

Tarim Saleem's format is correct but section is missing. Hadia's format must be the same.

Following is the correct format:
`Name  -   (Registration #)       Section`

**Peace!**

**Comment by hadiashahab** [comment]
File is updated with requested format.
